#pragma kernel CSInsertRawHeightToTex
#pragma kernel CSInsertRawAlphaToTex
#pragma kernel CSAlignVerticesToHeightmap
#pragma kernel CSGetCollisionMap
#include "rectangle_affect_settings.hlsl"
#include "packed_vertex.hlsl"

Texture2D<float> source_heightmap;
RWTexture2D<float> destination_heightmap;
Texture2D source_alphamap;
RWTexture2D<float4> destination_alphamap;
StructuredBuffer<float> chunk_heightmap;
StructuredBuffer<uint> chunk_alphamap;
StructuredBuffer<int2> map;
//StructuredBuffer<rectangle_affect_settings> deformation_rectangle_settings;
//StructuredBuffer<float> deformation_heightmap;
RWStructuredBuffer<packed_vertex> vertices;

float chunk_size;
float chunk_height;
float heightmap_chunk_resolution;
uint vertices_count;
uint vertices_width_count;
float normal_dx;
float normal_dt;
int chunk_coord_x;
int chunk_coord_y;
int map_size;
uint heightmap_start_x;
uint heightmap_start_y;
bool flip_x_y_when_import_raw_heightmap;

//collision request data
RWStructuredBuffer<float3> destination_collision_map;
StructuredBuffer<int2> collision_map_request;
int collision_chunks_count;
int collision_chunk_resolution;
float heightmap_pixel_size;
float collision_pixel_size;
float2 collision_offset;
float heightmap_pixel_size_uv_space;
float slots_count_inv;
SamplerState sampler_source_heightmap;
//int collision_chunk_size;
//float collision_to_heightmap_mul;

//#pragma kernel CSCopyHeightmap
//
//
//[numthreads(64,1,1)]
//void CSCopyHeightmap (uint id : SV_DispatchThreadID)
//{
//    destination_heightmap[id] = source_heightmap[id];
//}


//#pragma kernel CSApplyDeformation
//
//
//[numthreads(8,8,1)]
//void CSApplyDeformation (uint2 id : SV_DispatchThreadID)
//{
//    
//}

//#pragma kernel CSTestAlignSine
//float get_height_test_sine(float3 pos)
//{
//    return sin(pos.x * 0.5) * cos(pos.z * 0.5);
//}
//
//[numthreads(64,1,1)]
//void CSTestAlignSine (uint id : SV_DispatchThreadID)
//{
//    if (id > vertices_count)
//    {
//        return;
//    }
//    packed_vertex vert = vertices[id];
//    
//    vert.position.y = get_height_test_sine(vert.position);
//
//    // 3. Берем выборки высоты для расчета градиента (смещение по X и Z)
//    float height_x = get_height_test_sine(vert.position + float3(normal_dx, 0.0, 0.0));
//    float height_z = get_height_test_sine(vert.position + float3(0.0, 0.0, normal_dx));
//
//    // 4. Вычисляем частные производные (конечные разности)
//    float dfdx = (height_x - vert.position.y) * normal_dt;
//    float dfdz = (height_z - vert.position.y) * normal_dt;
//
//    // 5. Формируем и нормализуем вектор нормали
//    float y_len = sqrt(1 - (dfdx*dfdx + dfdz*dfdz));
//    float3 normal = float3(-dfdx, y_len, -dfdz);
//    vert.normal = normalize(normal);
//    
//    vertices[id] = vert;
//}



bool HalfToCoord(half value, out uint2 coord)
{
    uint rawBits = f32tof16((float)value);
    [branch] if (rawBits == 0)
    {
        coord = uint2(0,0);
        return false;
    }
    else
    {
        rawBits--;
        coord.x = rawBits & 0xFF;
        coord.y = (rawBits >> 8) & 0xFF;
        return true;
    }
}

float get_height_from_heightmap(int2 slot, int2 pixel_coord)
{
    const uint2 offset = uint2(1, 1);
    return source_heightmap[slot * (heightmap_chunk_resolution + 2) + pixel_coord + offset];
}

void set_height_to_heightmap(uint2 slot, uint2 pixel_coord, float value)
{
    const uint2 offset = uint2(1, 1);
    destination_heightmap[slot * (heightmap_chunk_resolution + 2) + pixel_coord + offset] = value;
}

void set_alpha_to_map(uint2 slot, uint2 pixel_coord, float4 value)
{
    const uint2 offset = uint2(1, 1);
    destination_alphamap[slot * (heightmap_chunk_resolution + 2) + pixel_coord + offset] = value;
}

void set_height_to_heightmap_border(uint2 slot, int2 pixel_coord, float value)
{
    const uint2 offset = uint2(1, 1);
    if (flip_x_y_when_import_raw_heightmap)
    {
        pixel_coord = pixel_coord.yx;
    }
    destination_heightmap[slot * (heightmap_chunk_resolution + 2) + pixel_coord + offset] = value;
}

void set_height_to_alpha_border(uint2 slot, int2 pixel_coord, float value)
{
    const uint2 offset = uint2(1, 1);
    destination_alphamap[slot * (heightmap_chunk_resolution + 2) + pixel_coord + offset] = value;
}

void sample_heightmap(int2 slot, float2 uv, out float height)
{
    float2 pix = float2(heightmap_pixel_size_uv_space, heightmap_pixel_size_uv_space);
    float2 uv_to_sample = (slot + uv * heightmap_pixel_size_uv_space * heightmap_chunk_resolution + pix) * slots_count_inv;
    
    height = source_heightmap.SampleLevel(sampler_source_heightmap, uv_to_sample, 0);
}

[numthreads(8,8,1)]
void CSInsertRawHeightToTex (uint2 id : SV_DispatchThreadID)
{
    if (id.x > heightmap_chunk_resolution || id.y > heightmap_chunk_resolution)
    {
        return;
    }
    
    int2 slot = map[chunk_coord_x * map_size + chunk_coord_y];
    if (slot.x != -1)
    {
        if (flip_x_y_when_import_raw_heightmap)
        {
            set_height_to_heightmap(slot, id.yx, chunk_heightmap[id.x * heightmap_chunk_resolution + id.y]);
        }
        else
        {
            set_height_to_heightmap(slot, id, chunk_heightmap[id.x * heightmap_chunk_resolution + id.y]);
        }
    }
    int2 border_id = id;
    if (id.x == 0)
    {
        border_id.x = -1;
    }
    else if (id.x == heightmap_chunk_resolution - 1)
    {
        border_id.x = heightmap_chunk_resolution;
    }

    if (id.y == 0)
    {
        border_id.y = -1;
    }
    else if (id.y == heightmap_chunk_resolution - 1)
    {
        border_id.y = heightmap_chunk_resolution;
    }

    if (border_id.x != id.x || border_id.y != id.y)
    {
        set_height_to_heightmap_border(slot, int2(id.x, border_id.y), chunk_heightmap[id.x * heightmap_chunk_resolution + id.y]);
        set_height_to_heightmap_border(slot, int2(border_id.x, id.y), chunk_heightmap[id.x * heightmap_chunk_resolution + id.y]);
        set_height_to_heightmap_border(slot, border_id, chunk_heightmap[id.x * heightmap_chunk_resolution + id.y]);
    }
}

float4 unpack_uint(uint value)
{
    float r = (float)((value >>  0) & 0xFF) / 255.0f;
    float g = (float)((value >>  8) & 0xFF) / 255.0f;
    float b = (float)((value >> 16) & 0xFF) / 255.0f;
    float a = (float)((value >> 24) & 0xFF) / 255.0f;

    return float4(r, g, b, a);
}

[numthreads(8,8,1)]
void CSInsertRawAlphaToTex (uint2 id : SV_DispatchThreadID)
{
    if (id.x > heightmap_chunk_resolution || id.y > heightmap_chunk_resolution)
    {
        return;
    }
    
    int2 slot = map[chunk_coord_x * map_size + chunk_coord_y];
    if (slot.x != -1)
    {
        if (flip_x_y_when_import_raw_heightmap)
        {
            set_alpha_to_map(slot, id.yx, unpack_uint(chunk_alphamap[id.x * heightmap_chunk_resolution + id.y]));
        }
        else
        {
            set_alpha_to_map(slot, id, unpack_uint(chunk_alphamap[id.x * heightmap_chunk_resolution + id.y]));
        }
    }
    int2 border_id = id;
    if (id.x == 0)
    {
        border_id.x = -1;
    }
    else if (id.x == heightmap_chunk_resolution - 1)
    {
        border_id.x = heightmap_chunk_resolution;
    }

    if (id.y == 0)
    {
        border_id.y = -1;
    }
    else if (id.y == heightmap_chunk_resolution - 1)
    {
        border_id.y = heightmap_chunk_resolution;
    }

    if (border_id.x != id.x || border_id.y != id.y)
    {
        set_height_to_alpha_border(slot, int2(id.x, border_id.y), unpack_uint(chunk_alphamap[id.x * heightmap_chunk_resolution + id.y]));
        set_height_to_alpha_border(slot, int2(border_id.x, id.y), unpack_uint(chunk_alphamap[id.x * heightmap_chunk_resolution + id.y]));
        set_height_to_alpha_border(slot, border_id, unpack_uint(chunk_alphamap[id.x * heightmap_chunk_resolution + id.y]));
    }
}


float get_height_from_heightmap(uint2 slot, uint2 pixel_coord, float2 interpolation)
{
    float top_left = get_height_from_heightmap(slot, pixel_coord);
    float top_right =  get_height_from_heightmap(slot, pixel_coord + int2(1, 0));
    float bottom_left =  get_height_from_heightmap(slot, pixel_coord + int2(1, 1));
    float bottom_right =  get_height_from_heightmap(slot, pixel_coord + int2(1, 1));
    float top = top_right + (top_left - top_right) * interpolation.x;
    float bottom = bottom_right + (bottom_left - bottom_right) * interpolation.x;
    return bottom + (top - bottom) * interpolation.y;
}

[numthreads(8,8,1)]
void CSAlignVerticesToHeightmap (uint2 id : SV_DispatchThreadID)
{
    if (id.x >= vertices_width_count || id.y >= vertices_width_count)
    {
        return;
    }
    int2 slot = map[chunk_coord_x * map_size + chunk_coord_y];
    if (slot.x == -1)
    {
        return;
    }
    
    packed_vertex vert = vertices[id.x * vertices_width_count + id.y];

    uint2 heightmap_space_id = id + uint2(heightmap_start_x, heightmap_start_y);
    vert.position.y =  get_height_from_heightmap(slot, heightmap_space_id);

    // 3. Берем выборки высоты для расчета градиента (смещение по X и Z)
    uint2 id_top_left = heightmap_space_id - uint2(1, 1);
    float x_dir = -1;
    if (id.x == 0)
    {
        x_dir = 1;
        id_top_left.x += 1;
    }
    float z_dir = -1;
    if (id.y == 0)
    {
        z_dir = 1;
        id_top_left.y += 1;
    }
    float height_x = get_height_from_heightmap(id_top_left, float2(normal_dt * x_dir, 0.0));
    float height_z = get_height_from_heightmap(id_top_left, float2(0.0, normal_dt * z_dir));

    // 4. Вычисляем частные производные (конечные разности)
    float dfdx = (height_x - vert.position.y) * normal_dx;
    float dfdz = (height_z - vert.position.y) * normal_dx;

    // 5. Формируем и нормализуем вектор нормали
    float y_len = sqrt(1 - dfdx*dfdx - dfdz*dfdz);
    float3 normal = float3(-dfdx * x_dir * chunk_size, y_len * chunk_height, -dfdz * z_dir * chunk_size);
    vert.normal = normalize(normal);
    vert.position.y *= chunk_height;
    vertices[id.x * vertices_width_count + id.y] = vert;
}


[numthreads(4,4,4)]
void CSGetCollisionMap (uint3 id : SV_DispatchThreadID)
{
    if (id.x > collision_chunk_resolution || id.y > collision_chunk_resolution || id.z >= collision_chunks_count)
    {
        return;
    }
    int2 collision_slot = collision_map_request[id.z];
    int2 collision_map_pixel_id = collision_slot * collision_chunk_resolution + id.xy; // start pixel in global space + id.xy
    float2 uv_heightmap_space = (collision_map_pixel_id + collision_offset) * collision_pixel_size / chunk_size; // remap space as a*b + c, get heightmap's map coordinate combined with chunk uv
    int2 map_index = floor(uv_heightmap_space); // get heightmap's map coordinate
    if (map_index.x < chunk_coord_x || map_index.y < chunk_coord_y)
    {
        return;
    }
    int2 slot = map[(map_index.x - chunk_coord_x) * map_size + map_index.y - chunk_coord_y];
    if (slot.x == -1)
    {
        return;
    }
    float2 uv = uv_heightmap_space - map_index; // get remains as uv_heightmap_space % 1, uv in heightmap chunk space
    //int2 pixel_coord = floor(uv * heightmap_chunk_resolution + float2(.5, .5));
    float height;
    sample_heightmap(slot, uv, height);

    int res_plus_one = collision_chunk_resolution + 1;
    destination_collision_map[id.y * res_plus_one + id.x + (res_plus_one * res_plus_one * id.z)] = float3(id.x * collision_pixel_size, height * chunk_height, id.y * collision_pixel_size);
}
