#include "rectangle_affect_settings.hlsl"
#include "packed_vertex.hlsl"

StructuredBuffer<float> source_heightmap;
//StructuredBuffer<float> neighbour_x_min_heightmap;
//StructuredBuffer<float> neighbour_x_max_heightmap;
//StructuredBuffer<float> neighbour_z_min_heightmap;
//StructuredBuffer<float> neighbour_z_max_heightmap;
RWStructuredBuffer<float> destination_heightmap;
StructuredBuffer<rectangle_affect_settings> deformation_rectangle_settings;
StructuredBuffer<float> deformation_heightmap;
RWStructuredBuffer<packed_vertex> vertices;
//const uint source_hm_id = 0;
//const uint xmin_hm_id = 1;
//const uint xmax_hm_id = 2;
//const uint zmin_hm_id = 3;
//const uint zmax_hm_id = 4;
float chunk_size;
float chunk_height;
uint vertices_count;
uint vertices_width_count;
uint heightmap_width_count;
float normal_dx;
float normal_dx_inv;
uint heightmap_start_x;
uint heightmap_start_y;



#pragma kernel CSCopyHeightmap


[numthreads(64,1,1)]
void CSCopyHeightmap (uint id : SV_DispatchThreadID)
{
    destination_heightmap[id] = source_heightmap[id];
}


#pragma kernel CSApplyDeformation


[numthreads(8,8,1)]
void CSApplyDeformation (uint2 id : SV_DispatchThreadID)
{
    
}

#pragma kernel CSTestAlignSine
float get_height_test_sine(float3 pos)
{
    return sin(pos.x * 0.5) * cos(pos.z * 0.5);
}

[numthreads(64,1,1)]
void CSTestAlignSine (uint id : SV_DispatchThreadID)
{
    if (id > vertices_count)
    {
        return;
    }
    packed_vertex vert = vertices[id];
    
    vert.position.y = get_height_test_sine(vert.position);

    // 3. Берем выборки высоты для расчета градиента (смещение по X и Z)
    float height_x = get_height_test_sine(vert.position + float3(normal_dx, 0.0, 0.0));
    float height_z = get_height_test_sine(vert.position + float3(0.0, 0.0, normal_dx));

    // 4. Вычисляем частные производные (конечные разности)
    float dfdx = (height_x - vert.position.y) * normal_dx_inv;
    float dfdz = (height_z - vert.position.y) * normal_dx_inv;

    // 5. Формируем и нормализуем вектор нормали
    float y_len = sqrt(1 - (dfdx*dfdx + dfdz*dfdz));
    float3 normal = float3(-dfdx, y_len, -dfdz);
    vert.normal = normalize(normal);
    
    vertices[id] = vert;
}

#pragma kernel CSAlignVerticesToHeightmap
float get_height_from_heightmap(uint2 id)
{
    return source_heightmap[id.x * heightmap_width_count + id.y];
}

float read_height(uint index/*, uint buffer_id*/)
{
    //[branch]
    //if(buffer_id == xmin_hm_id)
    //{
    //    return neighbour_x_min_heightmap[index];
    //}
    //else if(buffer_id == xmax_hm_id)
    //{
    //    return neighbour_x_max_heightmap[index];
    //}
    //else if(buffer_id == zmin_hm_id)
    //{
    //    return neighbour_z_min_heightmap[index];
    //}
    //else if(buffer_id == zmax_hm_id)
    //{
    //    return neighbour_z_max_heightmap[index];
    //}
    //else
    //{
        return source_heightmap[index];
    //}
}

float get_height_from_heightmap(uint2 id, float2 interpolation/*, uint heightmap_id*/)
{
    uint id_single = id.x * vertices_width_count + id.y;
    float top_left = read_height(id_single);
    float top_right =  read_height(id_single + vertices_width_count);
    float bottom_left =  read_height(id_single + 1);
    float bottom_right =  read_height(id_single + vertices_width_count + 1);
    float top = top_right + (top_left - top_right) * interpolation.x;
    float bottom = bottom_right + (bottom_left - bottom_right) * interpolation.x;
    return bottom + (top - bottom) * interpolation.y;
}

[numthreads(8,8,1)]
void CSAlignVerticesToHeightmap (uint2 id : SV_DispatchThreadID)
{
    if (id.x >= vertices_width_count || id.y >= vertices_width_count)
    {
        return;
    }
    packed_vertex vert = vertices[id.x * vertices_width_count + id.y];
    uint2 heightmap_space_id = id + uint2(heightmap_start_x, heightmap_start_y);
    vert.position.y = get_height_from_heightmap(heightmap_space_id);

    // 3. Берем выборки высоты для расчета градиента (смещение по X и Z)
    uint2 id_top_left = heightmap_space_id - uint2(1, 1);
    float x_dir = -1;
    if (id.x == 0)
    {
        x_dir = 1;
        id_top_left.x += 1;
    }
    float z_dir = -1;
    if (id.y == 0)
    {
        z_dir = 1;
        id_top_left.y += 1;
    }
    float height_x = get_height_from_heightmap(id_top_left, float2(normal_dx * x_dir, 0.0));
    float height_z = get_height_from_heightmap(id_top_left, float2(0.0, normal_dx * z_dir));

    // 4. Вычисляем частные производные (конечные разности)
    float dfdx = (height_x - vert.position.y) * normal_dx_inv * chunk_height;
    float dfdz = (height_z - vert.position.y) * normal_dx_inv * chunk_height;

    // 5. Формируем и нормализуем вектор нормали
    float y_len = sqrt(1 - (dfdx*dfdx + dfdz*dfdz));
    float3 normal = float3(-dfdx * x_dir, y_len, -dfdz * z_dir);
    vert.normal = normalize(normal);
    vert.position.y *= chunk_height;
    vertices[id.x * vertices_width_count + id.y] = vert;
}