#include "rectangle_affect_settings.hlsl"
#include "packed_vertex.hlsl"

Texture2D<float> source_heightmap;
RWTexture2D<float> destination_heightmap;
StructuredBuffer<float> chunk_heightmap;
StructuredBuffer<uint2> map;
//StructuredBuffer<rectangle_affect_settings> deformation_rectangle_settings;
//StructuredBuffer<float> deformation_heightmap;
RWStructuredBuffer<packed_vertex> vertices;
float chunk_size;
float chunk_height;
uint vertices_count;
uint vertices_width_count;
uint heightmap_width_count;
float normal_dx;
float normal_dt;
int chunk_coord_x;
int chunk_coord_y;
int map_size;
uint heightmap_start_x;
uint heightmap_start_y;



//#pragma kernel CSCopyHeightmap
//
//
//[numthreads(64,1,1)]
//void CSCopyHeightmap (uint id : SV_DispatchThreadID)
//{
//    destination_heightmap[id] = source_heightmap[id];
//}


//#pragma kernel CSApplyDeformation
//
//
//[numthreads(8,8,1)]
//void CSApplyDeformation (uint2 id : SV_DispatchThreadID)
//{
//    
//}

//#pragma kernel CSTestAlignSine
//float get_height_test_sine(float3 pos)
//{
//    return sin(pos.x * 0.5) * cos(pos.z * 0.5);
//}
//
//[numthreads(64,1,1)]
//void CSTestAlignSine (uint id : SV_DispatchThreadID)
//{
//    if (id > vertices_count)
//    {
//        return;
//    }
//    packed_vertex vert = vertices[id];
//    
//    vert.position.y = get_height_test_sine(vert.position);
//
//    // 3. Берем выборки высоты для расчета градиента (смещение по X и Z)
//    float height_x = get_height_test_sine(vert.position + float3(normal_dx, 0.0, 0.0));
//    float height_z = get_height_test_sine(vert.position + float3(0.0, 0.0, normal_dx));
//
//    // 4. Вычисляем частные производные (конечные разности)
//    float dfdx = (height_x - vert.position.y) * normal_dt;
//    float dfdz = (height_z - vert.position.y) * normal_dt;
//
//    // 5. Формируем и нормализуем вектор нормали
//    float y_len = sqrt(1 - (dfdx*dfdx + dfdz*dfdz));
//    float3 normal = float3(-dfdx, y_len, -dfdz);
//    vert.normal = normalize(normal);
//    
//    vertices[id] = vert;
//}


#pragma kernel CSInsertRawDataToTex

bool HalfToCoord(half value, out uint2 coord)
{
    uint rawBits = f32tof16((float)value);
    [branch] if (rawBits == 0)
    {
        coord = uint2(0,0);
        return false;
    }
    else
    {
        rawBits--;
        coord.x = rawBits & 0xFF;
        coord.y = (rawBits >> 8) & 0xFF;
        return true;
    }
}


float get_height_from_heightmap(uint2 slot, uint2 pixel_coord)
{
    return source_heightmap[slot * heightmap_width_count + pixel_coord];
}

void set_height_to_heightmap(uint2 slot, uint2 pixel_coord, float value)
{
    destination_heightmap[slot * heightmap_width_count + pixel_coord] = value;
}

[numthreads(8,8,1)]
void CSInsertRawDataToTex (uint2 id : SV_DispatchThreadID)
{
    if (id.x >= heightmap_width_count || id.y >= heightmap_width_count)
    {
        return;
    }
    uint2 slot = map[chunk_coord_x * map_size + chunk_coord_y];
    if (slot.x != -1)
    {
        set_height_to_heightmap(slot, id, chunk_heightmap[id.x * heightmap_width_count + id.y]);
    }
}

#pragma kernel CSAlignVerticesToHeightmap

float get_height_from_heightmap(uint2 slot, uint2 pixel_coord, float2 interpolation)
{
    float top_left = get_height_from_heightmap(slot, pixel_coord);
    float top_right =  get_height_from_heightmap(slot, pixel_coord + int2(1, 0));
    float bottom_left =  get_height_from_heightmap(slot, pixel_coord + int2(1, 1));
    float bottom_right =  get_height_from_heightmap(slot, pixel_coord + int2(1, 1));
    float top = top_right + (top_left - top_right) * interpolation.x;
    float bottom = bottom_right + (bottom_left - bottom_right) * interpolation.x;
    return bottom + (top - bottom) * interpolation.y;
}

[numthreads(8,8,1)]
void CSAlignVerticesToHeightmap (uint2 id : SV_DispatchThreadID)
{
    if (id.x >= vertices_width_count || id.y >= vertices_width_count)
    {
        return;
    }
    uint2 slot = map[chunk_coord_x * map_size + chunk_coord_y];
    if (slot.x == -1)
    {
        return;
    }
    
    packed_vertex vert = vertices[id.x * vertices_width_count + id.y];

    uint2 heightmap_space_id = id + uint2(heightmap_start_x, heightmap_start_y);
    vert.position.y =  get_height_from_heightmap(slot, heightmap_space_id);

    // 3. Берем выборки высоты для расчета градиента (смещение по X и Z)
    uint2 id_top_left = heightmap_space_id - uint2(1, 1);
    float x_dir = -1;
    if (id.x == 0)
    {
        x_dir = 1;
        id_top_left.x += 1;
    }
    float z_dir = -1;
    if (id.y == 0)
    {
        z_dir = 1;
        id_top_left.y += 1;
    }
    float height_x = get_height_from_heightmap(id_top_left, float2(normal_dt * x_dir, 0.0));
    float height_z = get_height_from_heightmap(id_top_left, float2(0.0, normal_dt * z_dir));

    // 4. Вычисляем частные производные (конечные разности)
    float dfdx = (height_x - vert.position.y) * normal_dx;
    float dfdz = (height_z - vert.position.y) * normal_dx;

    // 5. Формируем и нормализуем вектор нормали
    float y_len = sqrt(1 - dfdx*dfdx - dfdz*dfdz);
    float3 normal = float3(-dfdx * x_dir * chunk_size, y_len * chunk_height, -dfdz * z_dir * chunk_size);
    vert.normal = normalize(normal);
    vert.position.y *= chunk_height;
    vertices[id.x * vertices_width_count + id.y] = vert;
}