#pragma kernel CSMain

Texture2D<float4> source;
RWStructuredBuffer<float> result;
uint resx;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float a = source[id.x + id.y * resx].b;
    float b = source[id.x + id.y * resx + 1].b;
    float c = source[id.x + id.y * resx + resx].b;
    float d = source[id.x + id.y * resx + resx + 1].b;

    result[id.x + id.y * resx] = a + b + c + d;
}
